name: Python Setup Lab
run-name: "${{ github.actor }}'s Python Setup Workflow Run"

on:
  workflow_dispatch

jobs:
  setup-python-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show Python version
        run: python --version
